pipeline {
    agent any
    
    environment {
        VENV = ".venv"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',                   
                    credentialsId: 'github-creds',    
                    url: 'https://github.com/<your-username>/<your-repo>.git'
            }
        }

        stage('Setup Python Env') {
            steps {
                sh """
                python3 -m venv ${VENV}
                . ${VENV}/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt   
                """
            }
        }

        stage('Run Tests') {
            steps {
                sh """
                . ${VENV}/bin/activate
                pytest messaging_app --junitxml=report.xml      
                """
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
}
