# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: messaging-app-deployment
#   labels:
#     app: messaging-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: messaging-app
#   template:
#     metadata:
#       labels:
#         app: messaging-app
#     spec:
#       containers:
#         - name: messaging-app
#           image: mnutemesgen/messaging-app-web:latest
#           ports:
#             - containerPort: 8000
#           env:
#             - name: DJANGO_SETTINGS_MODULE
#               value: messaging_app.settings
#             - name: SECRET_KEY
#               valueFrom:
#                 secretKeyRef:
#                   name: django-secret
#                   key: secret-key
#             - name: DATABASE_URL
#               valueFrom:
#                 secretKeyRef:
#                   name: django-secret
#                   key: database-url
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: messaging-app
# spec:
#   selector:
#     app: messaging-app
#   ports:
#     - protocol: TCP
#       port: 8000
#       targetPort: 8000
#   type: ClusterIP

apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging
      version: blue
  template:
    metadata:
      labels:
        app: messaging
        version: blue
    spec:
      containers:
        - name: messaging
          image: mnutemesgen/messaging-app-web:blue  # Replace with your blue version image
          ports:
            - containerPort: 8000