# Generated by Django 5.2.4 on 2025-07-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_conversation_participants_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='conversation_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='participants_id',
            new_name='participants',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='conversation_id',
            new_name='conversation',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
